# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: PVE-Kernel-CI

on:
  # push:
  #  branches: 
  #   - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]
  watch:
     types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@master

      # 环境准备
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          #docker rmi `docker images -q`
          #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          #sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo wget -qO - http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg | sudo apt-key add -
          sudo echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" | sudo tee /etc/apt/sources.list.d/pve-install-repo.list
          sudo cat /etc/apt/sources.list
          sudo apt-get update 
          sudo apt-get install Git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev libpve-common-perl libtool perl-modules python-minimal sed tar zlib1g-dev
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          df -h

      # 下载源码
      - name: Clone source code
        run: |
         pwd         
         Git clone git://git.proxmox.com/git/pve-kernel.git
         ls -l -a

      # 修改patch文件
      - name: modify cade
        run: |
          cd ./pve-kernel/
          touch 123.deb
          ls -l -a

      # 上传固件
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: PVE_firmware_yfdoor
          path: ./pve-kernel/*.deb
