# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: PVE-Kernel-CI

on:
  # push:
  #  branches: 
  #   - master
  schedule:
     - cron: 0 0 1 * *
  # release:
  #   types: [published]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 项目初始
      - name: Checkout
        uses: actions/checkout@master

      # 环境准备
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d/*
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*

          sudo wget -qO - http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg | sudo apt-key add -
          sudo echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" | sudo tee /etc/apt/sources.list.d/pve-install-repo.list
          sudo apt-get update
          sudo apt-get install git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev libpve-common-perl libtool perl-modules python-minimal sed tar zlib1g-dev

          sudo echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main" | sudo tee /etc/apt/sources.list.d/eoan_package.list
          sudo apt-get update
          sudo apt-get install lz4

          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          df -h

      # 下载源码
      - name: Clone source code
        run: git clone git://git.proxmox.com/git/pve-kernel.git

      # 修改文件
      - name: Modify code
        run: |
          cp -f ./patches/kernel/* ./pve-kernel/patches/kernel/
          touch ./pve-kernel/123.deb

      # 开始编译
      #- name: Compile
      #  run: |
      #   cd ./pve-kernel/
      #   make V=s

      # 准备文件
      - name: Organize file
        run: |
          cd ./pve-kernel/
          mkdir PVE
          mv *.deb PVE
          zip -r PVE_file_yfdoor.zip PVE && cp -r -f PVE_file_yfdoor.zip ../PVE_file_yfdoor.zip

      # 上传文件
      - name: Upload file
        uses: actions/upload-artifact@master
        with:
          name: PVE_file_yfdoor
          path: ./pve-kernel/PVE

      # 更新项目
      - name: Package Push
        run: |
          git config --global user.email "yfdoor@github.com"
          git config --global user.name "yfdoor"
          git add PVE_file_yfdoor.zip
          git commit -m "Update pve-kernel package"
          git push
